platform :ios, 8.3

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'ReCaptcha_Example' do
  pod 'ReCaptcha/RxSwift', :path => '../'
  pod 'RxCocoa', '~> 4.0.0-alpha.1'

  target 'ReCaptcha_Tests' do
    inherit! :search_paths

    pod 'AppSwizzle', '~> 1.1'
  end
end
