platform :ios, 8.3

use_frameworks!

target 'ReCaptcha_Example' do
  pod 'ReCaptcha/RxSwift', :path => '../'
  pod 'RxCocoa', '= 4.0.0-alpha.1'

  target 'ReCaptcha_Tests' do
    inherit! :search_paths

    
  end
end
