codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "75...95"

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

ignore:
  - "Example/"
